name = "backend"
compatibility_date = "2023-12-01"

[vars]
# DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmQ3NzY4OTAtOWQxMC00MmIzLTk4ZGYtMDY5YWNkZTEyYWU2IiwidGVuYW50X2lkIjoiNTUyZTYyYzQxYjRjOWU4N2Q5NDhjM2IxN2UyMWI0OGEyNjBmYTMyMjFiODc3ZDVjNWZlNWMxYTM4YmQyMDQwYiIsImludGVybmFsX3NlY3JldCI6ImJhZmYzMDM0LThlYTgtNGY3MS1hNThjLTI0NmU3ZDQ4YjNkZCJ9.NsLU-0RTK7mHBzVwal-MS7on4NJTq1XmiM1kOi6N6Ow"
# DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDhhM2Q1YWUtYTJhMS00YjYyLTkzMTQtYTFlYzlhMzI1Y2E1IiwidGVuYW50X2lkIjoiZWZhYTkzNTE3NzMxYWE4MDQxOThlZWQ0YjkyMTQ2YTI3NjcxYTI4Yzg5YmIwZGE5M2RiNjc0MjQ3MWQ2ZWM5MyIsImludGVybmFsX3NlY3JldCI6ImU0ZTU5MjBiLTQzYmMtNGI1NC04ZmQ5LTMzZmEwODc0ZTE3NyJ9.2wwRflBxqDql1bHig82Sp2EmDyvMXyBAYJh7OwS02cU"
DATABASE_URL = ""
JWT_SECRET = ""

R2_URL = "https://pub-96c5670691c8435283fb5dea0d94a7e8.r2.dev"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "HONO_R2_UPLOAD"
bucket_name = "hono-r2-upload"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
